---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pulsepro-pulsepro-io-v1alpha1-pulseprodeployment
  failurePolicy: Fail
  name: mpulseprodeployment.kb.io
  rules:
  - apiGroups:
    - pulsepro.pulsepro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pulseprodeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pulsepro-pulsepro-io-v1alpha1-pulseprodeployment
  failurePolicy: Fail
  name: vpulseprodeployment.kb.io
  rules:
  - apiGroups:
    - pulsepro.pulsepro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pulseprodeployments
  sideEffects: None
