# permissions for end users to view pulseprorollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pulsepro-operator
    app.kubernetes.io/managed-by: kustomize
  name: pulseprorollout-viewer-role
rules:
- apiGroups:
  - pulsepro.pulsepro.io
  resources:
  - pulseprorollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pulsepro.pulsepro.io
  resources:
  - pulseprorollouts/status
  verbs:
  - get
