---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pulsepro.io
  resources:
  - pulseprodeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
